name: Upload

on:
  push:
    branches:
      - feat/preview

jobs:
  release:
    name: Upload qiniu
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "${{ secrets.QINIU_ENV_JS }}" > qiniu_env.js
          node upload.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
